baseURL = "https://example.org/"
languageCode = "en-us"
title = "e n d . o f . d A v e s"
theme = "hugo-PaperMod"
enableInlineShortcodes = true
enableEmojify = true

# Taxonomy
[taxonomies]
  category = "categories"
  tag = "tags"

# Main Menu
    [[menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/posts/"
        weight = 10
    [[main.menu]]
        identifier = "censorship"
        name = "censorship"
        url = "/censorship/"
        weight = 20
    [[menu.main]]
        identifier = "archive"
        name = "archive"
        url = "/archive/"
        weight = 60
    [[menu.main]]
        identifier = "boobs+"
        name = "boobs+"
        url = "/boobs+/"
        weight = 30
    [[main.menu]]
        identifier = "tag"
        name = "tags"
        url = "/tags/"
        weight = 50
    [[main.menu]]
        identifier = "notes"
        name = "notes"
        url = "/notes/"
        weight = 40

# PaperMod Theme - Home Mode 
[params.homeInfoParams]
Title = "Welcome üåê"
Content = "This is a blog site with lots of useful information about how to do different things on your computer."

[[params.socialIcons]]
name = "dev"
url = "https://dev.to/bafflingscience"
[[params.socialIcons]]
name = "pinterest"
url = "https://www.pinterest.com/bafflingscience/"
[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/prettynicecloud"
[[params.socialIcons]]
name = "github"
url = "github.com/bafflingscience"
[[params.socialIcons]]
name = "codepen"
url = "codepen.io"
[[params.socialIcons]]
name = "reddit"
url = "https://www.reddit.com/user/hooksaw_lazrblade"
[[params.socialIcons]]
name = "soundcloud"
url = "soundcloud.com"
[[params.socialIcons]]
name = "email"
url = "mailto:thedavidsofusa@gmail.com"

# Privacy Settings
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false
